version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=otsec
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d otsec"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend 
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/otsec
      - BACKEND_PORT=8080
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../anotherFrontend
      args:
        # This tells the frontend where to find the backend API inside Docker.
        NEXT_PUBLIC_API_BASE: http://backend:8080
    restart: always
    ports:
      - "9002:9002" # Exposes frontend on port 9002
    depends_on:
      - backend

volumes:
  db_data:
